config/routes.rb
Dcdecibel::Application.routes.draw do

  resources :neighborhoods

  resources :tickets

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :cities

  resources :events

  resources :venues

  resources :bands
  
  resources :users
  
  resources :scrapes

  resources :scrapes

  match 'about' => 'home#about'
  match 'contact' => 'home#contact'
  match 'scrapes/create' => 'scrapes#create'

  root :to => 'home#index'

end

app/models/band.rb
class Band < ActiveRecord::Base
  has_and_belongs_to_many :events, :join_table => :bands_events, :order => "name ASC"
  has_many :venues, :through => :events, :order => "name ASC"
  default_scope :order => "name ASC"
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  # GET /bands
  # GET /bands.json
  def index
    @bands = Band.all
    if (params["tokenformat"] and params["q"])
      tokenbands = Array.new
      @bands.each do |b|
        if (b.name.downcase.starts_with? params["q"].downcase )
          tokenbands.push({"value" => b.id, "name" => b.name})
        end
      end
      @bands = tokenbands
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json:  @bands }
    end
  end

  # GET /bands/1
  # GET /bands/1.json
  def show
    @band = Band.find(params[:id])
    if((@band.last_fm_id == nil or @band.last_fm_id == "") and !@band.is_classical and !@band.is_jazz and !@band.is_local)
      @band.last_fm_id = CGI.escape(@band.name)
    end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @band }
    end
  end

end

app/helpers/bands_helper.rb
module BandsHelper
end

app/views/bands/_form.html.erb
<%= form_for(@band) do |f| %>
  <% if @band.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@band.errors.count, "error") %> prohibited this band from being saved:</h2>

      <ul>
      <% @band.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :last_fm_id %><br />
    <%= f.text_field :last_fm_id %>
  </div>
  <div class="field">
    <%= f.label :wikipedia_id %><br />
    <%= f.text_field :wikipedia_id %>
  </div>
  <div class="field">
    <%= f.label :homepage_url %><br />
    <%= f.text_field :homepage_url %>
  </div>
  <div class="field">
    <%= f.label :bio %><br />
    <%= f.text_area :bio %>
  </div>
  <div class="field">
    <%= f.label :is_editors_choice %><br />
    <%= f.check_box :is_editors_choice %>
  </div>
  <div class="field">
    <%= f.label :editors_choice_note %><br />
    <%= f.text_area :editors_choice_note %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bands/edit.html.erb
<h1>Editing band</h1>

<%= render 'form' %>

<%= link_to 'Show', @band %> |
<%= link_to 'Back', bands_path %>

app/views/bands/index.html.erb
<h1>Listing bands</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Live fm</th>
    <th>Wikipedia</th>
    <th>Homepage url</th>
    <th>Bio</th>
    <th>Is editors choice</th>
    <th>Editors choice note</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bands.each do |band| %>
  <tr>
    <td><%= band.name %></td>
    <td><%= band.live_fm_id %></td>
    <td><%= band.wikipedia_id %></td>
    <td><%= band.homepage_url %></td>
    <td><%= band.bio %></td>
    <td><%= band.is_editors_choice %></td>
    <td><%= band.editors_choice_note %></td>
    <td><%= link_to 'Show', band %></td>
    <td><%= link_to 'Edit', edit_band_path(band) %></td>
    <td><%= link_to 'Destroy', band, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Band', new_band_path %>

app/views/bands/new.html.erb
<h1>New band</h1>

<%= render 'form' %>

<%= link_to 'Back', bands_path %>

app/views/bands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @band.name %>
</p>

<p>
  <b>Live fm:</b>
  <%= @band.last_fm_id %>
</p>

<p>
  <b>Wikipedia:</b>
  <%= @band.wikipedia_id %>
</p>

<p>
  <b>Homepage url:</b>
  <%= @band.homepage_url %>
</p>

<p>
  <b>Bio:</b>
  <%= @band.bio %>
</p>

<p>
  <b>Is editors choice:</b>
  <%= @band.is_editors_choice %>
</p>

<p>
  <b>Editors choice note:</b>
  <%= @band.editors_choice_note %>
</p>


<%= link_to 'Edit', edit_band_path(@band) %> |
<%= link_to 'Back', bands_path %>