config/routes.rb
Dcdecibel::Application.routes.draw do

  resources :neighborhoods

  resources :tickets

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :cities

  resources :events

  resources :venues

  resources :bands
  
  resources :users
  
  resources :scrapes

  resources :scrapes

  match 'about' => 'home#about'
  match 'contact' => 'home#contact'
  match 'scrapes/create' => 'scrapes#create'

  root :to => 'home#index'

end

app/models/neighborhood.rb
class Neighborhood < ActiveRecord::Base
  belongs_to :city
  has_many :venues
  has_many :events, :through => :venues
  default_scope :order => "name ASC"
end

app/helpers/neighborhoods_helper.rb
module NeighborhoodsHelper
end

app/views/neighborhoods/_form.html.erb
<%= form_for(@neighborhood) do |f| %>
  <% if @neighborhood.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@neighborhood.errors.count, "error") %> prohibited this neighborhood from being saved:</h2>

      <ul>
      <% @neighborhood.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :city_id %><br />
    <%= f.number_field :city_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/neighborhoods/edit.html.erb
<h1>Editing neighborhood</h1>

<%= render 'form' %>

<%= link_to 'Show', @neighborhood %> |
<%= link_to 'Back', neighborhoods_path %>

app/views/neighborhoods/index.html.erb
<h1>Listing neighborhoods</h1>

<table>
  <tr>
    <th>City</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @neighborhoods.each do |neighborhood| %>
  <tr>
    <td><%= neighborhood.city_id %></td>
    <td><%= neighborhood.name %></td>
    <td><%= link_to 'Show', neighborhood %></td>
    <td><%= link_to 'Edit', edit_neighborhood_path(neighborhood) %></td>
    <td><%= link_to 'Destroy', neighborhood, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Neighborhood', new_neighborhood_path %>

app/views/neighborhoods/new.html.erb
<h1>New neighborhood</h1>

<%= render 'form' %>

<%= link_to 'Back', neighborhoods_path %>

app/views/neighborhoods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>City:</b>
  <%= @neighborhood.city_id %>
</p>

<p>
  <b>Name:</b>
  <%= @neighborhood.name %>
</p>


<%= link_to 'Edit', edit_neighborhood_path(@neighborhood) %> |
<%= link_to 'Back', neighborhoods_path %>